version: '3'

services:
  python-service:
    image: python:3.9
    volumes:
      - ./app:/app
    working_dir: /app
    # command: python script.py
    tty: true

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql